// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/id_publisher.go -package=mocks -exclude_interfaces=Consumer,Publisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIDPublisher is a mock of IDPublisher interface.
type MockIDPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockIDPublisherMockRecorder
	isgomock struct{}
}

// MockIDPublisherMockRecorder is the mock recorder for MockIDPublisher.
type MockIDPublisherMockRecorder struct {
	mock *MockIDPublisher
}

// NewMockIDPublisher creates a new mock instance.
func NewMockIDPublisher(ctrl *gomock.Controller) *MockIDPublisher {
	mock := &MockIDPublisher{ctrl: ctrl}
	mock.recorder = &MockIDPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDPublisher) EXPECT() *MockIDPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIDPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIDPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIDPublisher)(nil).Close))
}

// Publish mocks base method.
func (m *MockIDPublisher) Publish(subject string, content []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", subject, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockIDPublisherMockRecorder) Publish(subject, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockIDPublisher)(nil).Publish), subject, content)
}

// PublishWithID mocks base method.
func (m *MockIDPublisher) PublishWithID(subject, msgID string, content []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishWithID", subject, msgID, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishWithID indicates an expected call of PublishWithID.
func (mr *MockIDPublisherMockRecorder) PublishWithID(subject, msgID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishWithID", reflect.TypeOf((*MockIDPublisher)(nil).PublishWithID), subject, msgID, content)
}
