version: "3"

tasks:
  create_logs_folder:
    desc: "Create logs folder for docker volume purposes."
    dir: ../
    cmds:
      - mkdir -p logs

  tests:
    desc: "Run tests and save coverage to coverage folder."
    aliases:
      - test
    dir: ../
    cmds:
      - mkdir -p ./coverage
      - go test -v -shuffle=on -coverprofile ./coverage/coverage.out -coverpkg=./... ./... -tags=integration
      - go tool cover -html ./coverage/coverage.out -o ./coverage/coverage.html

  benchmarks:
    desc: "Run benchmarks."
    aliases:
      - bench
    dir: ../
    cmd: go test -v ./... -bench=. -run=xxx -benchmem >> bench.txt

  linters:
    desc: "Run linters."
    aliases:
      - lint
    dir: ../
    cmd: golangci-lint run -v --fix
