version: "3"

tasks:
  create_logs_folder:
    desc: "Create logs folder for docker volume purposes."
    dir: ../
    cmds:
      - mkdir -p logs

  tests:
    desc: "Run tests and save coverage to ./tests/coverage folder."
    aliases:
      - test
    dir: ../
    cmds:
      - mkdir -p ./coverage
      - go test -v -coverprofile ./coverage/coverage.out -coverpkg=./... ./...
      - go tool cover -html ./coverage/coverage.out -o ./coverage/coverage.html

  linters:
    desc: "Run linters."
    aliases:
      - lint
    dir: ../
    cmd: golangci-lint run -v --fix
